apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-country-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/<NAMESPACE>/hello-country-service:latest
          env:
            - name: COUNTRY_CODE
              value: EN
          ports:
            - containerPort: 8080
